### ISSUE TITLE
Website not loading

### ISSUE THREAD

**Issue by Meavis** [enricozb/remarkable-templates#1]
Once I open the website, it will briefely show the loading icon (the square with the dots) after which the dots dissapear and it only shows the black square and the header. Trying this on different devices and different browsers had the same effect.

![Screenshot 2020-12-14 172936](https://user-images.githubusercontent.com/31929288/102107451-09e19e00-3e32-11eb-86cf-6860f3562d61.png)

**Comment by enricozb** [comment]
Hey thanks so much for raising this issue, it should be fixed now, looks like there was a google storage issue. Please try it again.

Also what setup are you running? Browser & os/window manager. I'm super curious because I cannot tell at all from the screenshot.

**Comment by Meavis** [comment]
Hey, thanks for looking at it this quickly, it works now! As for browser and OS, I use OperaGX and just plain windows 10. I just cropped the image a bit at the top and bottom because of personal info in some of the other tabs. Underneath you can see what it normally looks like.
[cid:image002.png@01D6D2E8.D653A560]

Cheers,

Allysha
